version: "2.3"
services:
  app:
    depends_on:
      mysql:
        condition: service_healthy
    image: medonagy45/node-latest
    ports:
      - 3000:3000
    # environment:
    # MYSQL_DB_HOST: mysql
    # MYSQL_DB_PORT: 3306
    # MYSQL_DB_NAME: test1
    # MYSQL_DB_USER: root
    # MYSQL_DB_PASSWORD: root
    env_file:
      - ./.env
    links:
      - mysql:mysql

  mysql:
    container_name: mysqldb
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
    environment:
      MYSQL_DATABASE: "test1"
      # MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3307:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  dbdata:
